config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root controller: :articles, action: :index

  resources :articles, only: [:index, :show]

  namespace :cms do
    resources :articles
  end

end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image
  validates_presence_of  :title, :lede, :body
  belongs_to :user
  belongs_to :category

  validates_presence_of  :title, :lede, :body, :category_id, :user_id
end

app/models/category.rb
class Category < ApplicationRecord
    validates_presence_of :name

    has_many :articles
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  
  validates_presence_of :first_name, :last_name, :email, :encrypted_password

  enum role: { member: 0, journalist: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  def configure_permitted_parameters
    attributes = [:first_name, :last_name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :lede, :body, :author, :image))
 
        if @article.save
            redirect_to articles_path, notice: "Article is successfully created."
        else
            render 'new'
        end
    end
    
    def show
        @article = Article.find(params[:id])
    end

end

app/controllers/cms/articles_controller.rb
class Cms::ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to cms_articles_path, notice: "Article is successfully created."
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to cms_articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to cms_articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :lede, :body, :image, :category_id, :user_id)
  end

end

app/views/articles/index.html.haml
-if user_signed_in?
  -if current_user.role == 'journalist'
    %p=link_to "My account", cms_articles_path 

%h2= t 'Articles'
- @articles.each do |article|
  %h3= link_to "#{article.title}", article
  %p= article.category.name
  %p= image_tag("article.jpg")  
  %p= article.lede
  %p 
    Author:
    = article.user.first_name
  %p= article.created_at.strftime("%F")

app/views/articles/new.html.haml
= form_with model: @article, url: articles_path do |form|
  - if @article.errors.any?
    %h2
      = pluralize(@article.errors.count, "error")
      prohibited
      this article from being saved:
    %ul
      - @article.errors.full_messages.each do |msg|
        %li= msg 
  %p
    = form.label :title
    = form.text_field :title
  %p
    = form.label :lede
    = form.text_area :lede
  %p
    = form.label :body
    = form.text_area :body
  %p
    = form.label :author
    = form.text_field :author
  %p
    = form.label :image
    = form.file_field :image
  %p
    = form.submit

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.category.name
%p= image_tag @article.image if @article.image.attached?  
%p= @article.body
%p 
  Author:
  = @article.user.first_name
%p= @article.created_at.strftime("%F")
= link_to 'back', articles_path 

app/views/cms/articles/edit.html.haml
= form_with model: @article, url: cms_article_path  do |form|
  - if @article.errors.any?
    %h2
      = pluralize(@article.errors.count, "error")
      prohibited
      this article from being saved:
    %ul
      - @article.errors.full_messages.each do |msg|
        %li= msg 
  %p
    = form.label :title
    = form.text_field :title
  %p
    = form.label :lede
    = form.text_area :lede
  %p
    = form.label :body
    = form.text_area :body
  %p
    = form.label :image
    = form.file_field :image
    = form.hidden_field :user_id, value: current_user.id
  %br
    = form.label :category
    .Category= form.collection_select :category_id, Category.all, :id, :name 

  %p
    = form.submit


= link_to 'Back to list', cms_articles_path

app/views/cms/articles/index.html.haml
= link_to 'New Article', new_cms_article_path

%h1 List of articles
%table
  %tr
    %th{align: "left"} Title
    %th{align: "left"} Content
    %th
  - @articles.each do |article|
    -if article.user == current_user
      %tr
        %td= article.title
        %td= article.lede
        %td= link_to 'Show', article_path(article)
        %td= link_to 'Edit', edit_cms_article_path(article)
        %td= link_to 'Delete', cms_article_path(article),  |
            method: :delete,                               |
            data: { confirm: 'Are you super-duper sure?' } |

app/views/cms/articles/new.html.haml
= form_with model: @article, url: cms_articles_path  do |form|
  - if @article.errors.any?
    %h2
      = pluralize(@article.errors.count, "error")
      prohibited
      this article from being saved:
    %ul
      - @article.errors.full_messages.each do |msg|
        %li= msg 
  %p
    = form.label :title
    = form.text_field :title
  %p
    = form.label :lede
    = form.text_area :lede
  %p
    = form.label :body
    = form.text_area :body
  %p
    = form.label :author
    = form.text_field :author
  %p
    = form.label :image
    = form.file_field :image
  %br
    = form.label :category
    .Category= form.collection_select :category_id, Category.all, :id, :name 

  %p
    = form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Craftynews
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{async: "", src: "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
    :javascript
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-9138077038022871",
        enable_page_level_ads: true
      });
  %body
    = link_to_unless_current  "English", locale: 'en' 
    = link_to_unless_current  "Svenska", locale: 'sv' 
    = render partial: 'partials/navbar'

    = notice
    = alert

    = yield

app/views/partials/_navbar.html.haml
.navbar
  %p= link_to 'Home', root_path

-if user_signed_in?
  %p="Hello, #{current_user.first_name}!"
  %p=link_to "Log out", destroy_user_session_path, method: :delete
-else
  %p=link_to "Sign up", new_user_registration_path
  %p=link_to "Log in", new_user_session_path